config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  resources :baskets do
    put :reset
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :products
  belongs_to :user, optional: true

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :basket, optional: true

  enum vat_type: [:zero, :reduced, :standard]

  def vat_total
    #calculating VAT for the purchased items
    # if vat_rate is zero
    # then vat is 0% of product's price
    # if vat_rate is reduced
    # then vat is 5% of product's price
    # if vat_rate is standard
    # then vat is 20% of product's price

    if zero?
      if quantity == 2
        # every second Scotland Flag goes with £5 discount.
        self.price = self.price - (20 * 0.05)
        self.save
        self.price
      else
        self.price
      end
    elsif reduced?
      self.price * 0.05
    elsif standard?
      self.price * 0.2
    end
  end

  def total
    #adding VAT for the purchased items to product's price
    if zero?
      if quantity > 0
        (self.price)* quantity
      else
        self.price
      end
    else
      if quantity > 0
        (self.price + self.vat_total) * quantity
      else
        self.price + self.vat_total
      end

    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :basket

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    if resource
      products_path
    else
      root_path
    end
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController

  def create
    @basket = Basket.first_or_initialize
    @basket.user = current_user

    product = Product.find(params[:product_id])
    product.update_attributes(quantity: product.quantity + 1)

    @basket.products << product
    @basket.save

    @basket.total_price = @basket.products.all.sum { |p| p.total }
    @basket.save

    #if customer spends more than £70 - he should get 12% off his purchase.
    if @basket.total_price > 70
      discounted_price = (@basket.total_price * 12) / 100
      @basket.total_price = @basket.total_price - discounted_price
      @basket.save
    end

    redirect_to products_path
  end

  def reset
    @basket = Basket.find(params[:basket_id])
    @basket.products.update_all(quantity: 0)
    @basket.products.zero.update_all(price: 20.0)
    @basket.update_attributes(product_ids: nil, total_price: nil)
    redirect_to products_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info'}[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "text-center alert alert-dismissible fade show #{bootstrap_class_for(msg_type.to_sym)}") do
        concat content_tag(:button, 'x', class: 'close', data: {dismiss: 'alert'})
        concat simple_format(message)
      end)
    end
    nil
  end

  def active_class(path)
    return_class = ''
    if path.class == Array
      if path.any? { |str| request.path.include? str }
        return_class = 'active'
      end
    else
      if request.path.include?(path)
        return_class = 'active'
      end
    end
    return_class
  end

  def formatted_price(price)
    if price.blank?
      'N/A'
    else
      "€#{formatted_decimal(price)}"
    end
  end

  def formatted_decimal(number)
    if number.blank?
      ''
    else
      number_with_precision(number, precision: 2, delimiter: ',')
    end
  end

end

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-light.sticky-top.bg-secondary.flex-md-nowrap.p-0
  a.navbar-brand.col-md-2.mr-0.text-white href="#" CheckoutSystem
  -if current_user
    .d-flex.justify-content-around.col-10
      div
      .navbar-nav
        = link_to 'Products', products_path, class: 'nav-link text-white m-0 '
      .navbar-nav.mt-2
        span.text-white style= 'margin-left: 800px;' #{current_user.email}
      .navbar-nav
        = link_to 'Sign out', destroy_user_session_path, data: {confirm: 'Are you sure?', title: 'Sign out'}, class: 'nav-link text-white', method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CheckoutSystem
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    #wrap
      = render 'layouts/navbar'
      .container-fluid
        .row
          main.col.pt-3.px-4 role="main"
            #main-content.mb-5
              = flash_messages
              = yield

app/views/products/index.html.slim
table.table.table-striped.table-hover
  thead
    tr
      th #
      th Code
      th Name
      th Price
      th Quantity
      th Vat Total
      th Sub Total
      th Actions
  tbody
    - @products.each do |product|
      tr
        td = product.id
        td
          = product.code
        td
          =product.name
        td = formatted_price(product.price)
        td = product.quantity
        td = product.vat_total
        td = product.total
        td = link_to 'Add To Cart', baskets_path(product_id: product.id), class: 'btn btn-sm btn-info', method: :post
    tr
      td
        span Grand Total
        '
        = current_user.basket&.total_price || 0.0
      td
        = link_to 'Reset', basket_reset_path(basket_id: current_user.basket&.id.to_i), class: 'btn btn-sm btn-info', method: :put

.d-flex.justify-content-end.flex-wrap